// Code generated by MockGen. DO NOT EDIT.
// Source: ./httpservice.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	repository "homework/Homework-1/internal/pkg/repository"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPVZRepo is a mock of PVZRepo interface.
type MockPVZRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPVZRepoMockRecorder
}

// MockPVZRepoMockRecorder is the mock recorder for MockPVZRepo.
type MockPVZRepoMockRecorder struct {
	mock *MockPVZRepo
}

// NewMockPVZRepo creates a new mock instance.
func NewMockPVZRepo(ctrl *gomock.Controller) *MockPVZRepo {
	mock := &MockPVZRepo{ctrl: ctrl}
	mock.recorder = &MockPVZRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPVZRepo) EXPECT() *MockPVZRepoMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockPVZRepo) Add(ctx context.Context, pvz *repository.PVZ) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, pvz)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockPVZRepoMockRecorder) Add(ctx, pvz interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockPVZRepo)(nil).Add), ctx, pvz)
}

// Delete mocks base method.
func (m *MockPVZRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPVZRepoMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPVZRepo)(nil).Delete), ctx, id)
}

// GetById mocks base method.
func (m *MockPVZRepo) GetById(ctx context.Context, id int64) (*repository.PVZ, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(*repository.PVZ)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockPVZRepoMockRecorder) GetById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockPVZRepo)(nil).GetById), ctx, id)
}

// ListOfPVZ mocks base method.
func (m *MockPVZRepo) ListOfPVZ(ctx context.Context) ([]*repository.PVZ, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOfPVZ", ctx)
	ret0, _ := ret[0].([]*repository.PVZ)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOfPVZ indicates an expected call of ListOfPVZ.
func (mr *MockPVZRepoMockRecorder) ListOfPVZ(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOfPVZ", reflect.TypeOf((*MockPVZRepo)(nil).ListOfPVZ), ctx)
}

// Update mocks base method.
func (m *MockPVZRepo) Update(ctx context.Context, pvz *repository.PVZ) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, pvz)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPVZRepoMockRecorder) Update(ctx, pvz interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPVZRepo)(nil).Update), ctx, pvz)
}
