# Указываем базовый образ
FROM postgres:13

# Устанавливаем переменные окружения
ENV POSTGRES_DB=test \
    POSTGRES_USER=test \
    POSTGRES_PASSWORD=test

# Пробрасываем порт контейнера
EXPOSE 5432
